version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node:12.13.0

    steps:
      - checkout
      - run:
          name: Run unit tests
          environment:
            NODE_ENV: "test"
          command: |
            npm run test

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            TAG="latest"
            docker build -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO:latest .
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $AWS_ECR_REPO
      - add_ssh_keys

      - run:
          name: add vps to trusted hosts
          command: |
            ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

      - run:
          name: ssh into vm
          command: |
            ssh -o StrictHostKeyChecking=no -o SendEnv="AWS_ECR_ACCOUNT_URL" -o SendEnv="AWS_ECR_REPO" -o SendEnv="AWS_ACCESS_KEY_ID" -o SendEnv="AWS_SECRET_ACCESS_KEY_ID" root@$DEPLOY_HOST 'aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL && docker stop $AWS_ECR_REPO; docker rm $AWS_ECR_REPO; docker pull $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO && docker run --name=$AWS_ECR_REPO --restart=alawys $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO:latest'
