version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws-ecr: circleci/aws-ecr@6.8.2

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node:12.13.0

    steps:
      - checkout
      - run:
          name: Run unit tests
          environment:
            NODE_ENV: "test"
          command: |
            npm run test

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            TAG="latest"
            docker build -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO:latest .
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $AWS_ECR_REPO
