version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node:12.13.0

    steps:
      - checkout
      - run:
          name: Run unit tests
          environment:
            NODE_ENV: "test"
          command: |
            npm run test

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            TAG="latest"
            docker build -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO:latest .
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $AWS_ECR_REPO
      - add_ssh_keys

      - run:
          name: add vps to trusted hosts
          command: |
            ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

      - run:
          name: ssh into vm
          command: |
            ssh root@$DEPLOY_HOST <<'ENDSSH'
            touch test.log
            echo "test" > test.log
            ENDSSH
      # docker pull myuser/myapp
      # docker stop my-app
      # docker rm my-app
      # docker run --name=my-app --restart=always -v $PWD:/app -d myuser/myapp
